version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - server
    tty: true
    stdin_open: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    tty: true
    stdin_open: true
