name: Upload Website to s3 bucket

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}
        AWS_REGION: 'us-east-1'   
        SOURCE_DIR: './'    
