name: Upload Website to S3 bucket
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          TF_USER_AWS_KEY: ${{ secrets.TF_USER_AWS_KEY }}
          TF_USER_AWS_SECRET: ${{ secrets.TF_USER_AWS_SECRET }}
          AWS_S3_BUCKET: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
          AWS_REGION: us-east-1
          SOURCE_DIR: './'
